### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by penelopepg** [brainhack-school2020/Biosignal-Emotions-BHS-2020#1]
Hi!

Your project seems very promising. I have a few questions for  you.
1. Do you believe the devide will be available in the near future?
2. Which biosignals do you plan on using?

Good luck with everything!

Pénélope

**Comment by danibene** [comment]
Hello! Thanks for your questions :)

1. Given that our data collection has been postponed due to the pandemic, I doubt it :(
2. We were planning on using [biosignals extracted from in-ear audio recordings](https://ieeexplore.ieee.org/abstract/document/7959201/?casa_token=9Sehjko8ldIAAAAA:eOEoM0K61kdivAvAe_xcnKWtyqyELBIEsUlzk3gQO_ID1FZ7cIyxMsCu6TWnLXmgLL781FPvgbg ), likely the heart rate. But to obtain data for training the emotion recognition system, we were going to build off of an existing study where electrodermal activity, skin temperature, and blood volume pulse is recorded with a finger sensor, so that will give us the opportunity to compare the in-ear biosignals to another modality.

**Comment by danibene** [comment]
Hello! Thanks for your questions :)

Given that our data collection has been postponed due to the pandemic, I doubt it :(
We were planning on using biosignals extracted from in-ear audio recordings, likely the heart rate. But to obtain data for training the emotion recognition system, we were going to build off of an existing study where electrodermal activity, skin temperature, and blood volume pulse is recorded with a finger sensor, so that will give us the opportunity to compare different modalities.

**Comment by danibene** [comment]
Hello! Thanks for your questions :)

Given that our data collection has been postponed due to the pandemic, I doubt it :(
We were planning on using [biosignals extracted from in-ear audio recordings](https://ieeexplore.ieee.org/abstract/document/7959201/?casa_token=9Sehjko8ldIAAAAA:eOEoM0K61kdivAvAe_xcnKWtyqyELBIEsUlzk3gQO_ID1FZ7cIyxMsCu6TWnLXmgLL781FPvgbg), likely the heart rate. But to obtain data for training the emotion recognition system, we were going to build off of an existing study where electrodermal activity, skin temperature, and blood volume pulse is recorded with a finger sensor, so that will give us the opportunity to compare different modalities.

**Comment by beapdk** [comment]
Hi ! Based on an answer from your teammate Achraf, he mentioned you were thinking about maybe choosing PSD and phase as EEG features. I was curious if you had any frequency range in mind to correlate with the rest of your biosignal data features and emotion recognition ? It seems like you have a lot of data options to choose from for your ambitious (and great) project, so I was wondering which type of classifier you had in mind to integrate all these different types of data in your model ?

**Comment by danibene** [comment]
Hi @beapdk :) We were thinking of extracting many "potential" features and then only using the most relevant features for emotion recognition (e.g.  if p < 0.05) based on the training set. So for example, we would use the PSD from theta, alpha, beta, and gamma bands as potential features, and then if p < 0.05 only for the alpha and gamma bands we would only include those as features for the classifier. Regarding your second question: right now, it isn't our goal to build a multimodal classifier - first we wanted to see what results we could get using just one biosignal. If we have time though, it would be interesting to try out data fusion. We're very open to suggestions if you have any!
